Enumerables Project - Rose and Necmi
necmigunduz/rose_necmi_enumarables pull request #1
Opened 2021-01-08 15:43 UTC by necmigunduz

In this project, we did :

- create an algorithm for using enumerable methods in Ruby

We would kindly request you to review my project, and provide me your feedback to improve it. If you find it satisfactory, we would kindly request you to approve it.

2021-01-08 19:16 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED 🛑 

Hello team! 👋 

A great effort in this project so far 👍 
However, we still need to implement some changes in order to get the project approved 💪 
Kindly check my comments below 👇  apply the changes and request a new code review once done ⏩ 
Good luck! 😃 
## Mandatory changes
- Your branch is in conflict with the development branch due to the readme file, kindly fix that issue
- Kindly remove all commented out code from your main file, if you need to add example cases you can add it in another file
- my_all, my_nona and my_any should end with a '?' per convention since are returning true or false, kindly modify it

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_each returns an Enumerator if no block is given
#my_each when a block is given when self is an array returns the array itself after calling the given block once for each element in self
#my_each when a block is given when self is a range returns the range itself after calling the 
given block once for each element in self
#my_each when a block is given when self is a range behaves like #each calls the given block once for each element in self
#my_each when a block is given when self is a hash behaves like #each calls the given block once for each element in self

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_each_with_index returns an enumerator if no block is given
#my_each_with_index when a block is given when self is an array returns the array itself after 
calling the given block once for each element in self
#my_each_with_index when a block is given when self is a range returns the range itself after 
calling the given block once for each element in self
#my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
#my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_select returns an array containing all elements of enum for which the given block returns a true value
#my_select returns an array containing all elements of enum for which the given block returns a true value::range

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_all? returns true if the block never returns false or nil
#my_all? returns false if the block returns false or nil
#my_all? returns false if the block returns false or nil::range
#my_all? does not mutate the original array
#my_all? when no block or argument is given returns true when none of the collection members are false or nil
#my_all? when no block or argument is given returns false when one of the collection members are false or nil
#my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
#my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
#my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class
#my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
#my_all? when a Regex is passed as an argument returns false if any of the collection does not match the Regex
#my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
#my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_any? returns true if the block ever returns a value other than false or nil
#my_any? returns false if the block ever returns a value false or nil
#my_any? returns false if the block ever returns a value false or nil::range
#my_any? does not mutate the original array
#my_any? when no block or argument is given returns true if at least one of the collection is 
not false or nil
#my_any? when no block or argument is given returns false if at least one of the collection is not true
#my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
#my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
#my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex
#my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
#my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
#my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_none? returns true if the block never returns true for all elements
#my_none? returns false if the block ever returns true for all elements
#my_none? returns false if the block ever returns true for all elements::range
#my_none? does not mutate the original array
#my_none? when no block or argument is given returns true only if none of the collection members is true
#my_none? when no block or argument is given returns false only if one of the collection members is true
#my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
#my_none? when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
#my_none? when a class is passed as an argument returns false if any of the collection is a member of such class
#my_none? when a Regex is passed as an argument returns true if none of the collection matches the Regex
#my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex
#my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
#my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_count returns the number of items in enum through enumeration
#my_count returns the number of items in enum through enumeration::range
#my_count counts the number of items in enum that are equal to item if an argument is given   
#my_count counts the number of elements yielding a true value if a block is given

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_map returns a new array with the results of running a given block once for every element in enum.
#my_map returns a new array with the results of running a given block once for every element in enum::range
#my_map returns an Enumerator if no block is given
#my_map accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum.
#my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
#my_map does not mutate the original array

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
#my_inject when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range
#my_inject when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
#my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
#my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
#my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
#my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +  end
this feature must work in my_map, you do not need to create a new method

2021-01-08 19:16 UTC, javitocor commented on enumerables.rb
> +end
fix my_index and it will work

2021-01-08 22:10 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__So far, you've done an amazing job.
However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] A lot of test cases are still failing in your project. Let's check some of them.
- **#my_each**
  - should return an Enumerator if no block is given. You used `to_enumerator` in this case. You should use the `to_enum` method.
  - When a block is given when self is an array, #my_each should return the array itself after calling the given block once for each element in self
  - There's a name error when self is a range and block is given: `NameError: undefined local variable or method `length' for 5..50:Range`
 - **#my_each_with_index**
  - should return an Enumerator if no block is given. You used `to_enumerator` in this case. You should use the `to_enum` method.
  - when a block is given when self is an array, it should return the array itself after calling the given block once for each element in self.
  - There's a name error when self is a range and block is given: `NameError: undefined local variable or method `length' for 5..50:Range`
- **#my_select**
  - should return an array containing all elements of enum for which the given block returns a true value.

- **#my_all**
  - should return false if the block returns false or nil
  - should return false if the block returns false or nil::range
  - when no block or argument is given, it should return true when none of the collection members are false or nil
  - when no block or argument is given, it should return false when one of the collection members is false or nil
  - when a class is passed as an argument, it should return true if all of the collection is a member of such class::Integer

- [ ] Please note: for all the enumerables methods, you should consider when they are being used on the different data structures. 
- [ ] Not all methods that work for one data structure works for the others. For instance, the length of an array can be obtained with `array.length`. This is not true for a range of values. using the `.length` method on the range data structure will always raise the error: `NameError: undefined local variable or method `length' for 5..50:Range`. Take note of this as it's very important.
- [ ] Although there are other failed instances, the above points, I believe, should guide you on how to effect changes on other enumerable methods.

* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-01-09 12:01 UTC, mcrd25 requested changes
# Changes Required :mag: 

Hi Team! :wave: 

Thanks a lot for attempting the changes requested, your effort is noted!  :slightly_smiling_face: 

As mentioned before, a lot of our test cases are still failing. 
It would be redundant for me to repeat what has already mentioned but what I will recommend is that you please take a look at each method one at a time and take a look at the resource I listed below.

I did also give you some help with the `my_inject` since in my experience of reviewing that's the most troublesome method.

#### Useful Resources

**Documentation on original methods**
https://ruby-doc.org/core-2.7.0/Enumerable.html

***Please makes changes and submit another review request.
If you have any questions, let me know here or email (preferably) or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

If you liked my review, consider upskilling me on LinkedIn. And please do connect. [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2021-01-09 12:01 UTC, mcrd25 commented on enumerables.rb
> +  def my_inject(beg = nil, sym = nil)
ADDITIONAL HINT :bulb: 
 
consider if one of your args is a symbol.
    If a symbol is specified, it should combine each element of the collection by applying the symbol as a named method.
    You can read more about enumerable methods here: https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-inject
    
You may use the [`is_a?`](https://ruby-doc.org/core-2.7.0/Object.html#method-i-is_a-3F) method in the following manner to help you solve this issue:
        ```ruby
            is_a?(Symbol)
        ```
    
You may also use the [`send`](https://ruby-doc.org/core-2.7.0/Object.html#method-i-send) method to help handle the symbol.
    
Hope this helps 🙏

2021-01-09 12:03 UTC, mcrd25 commented
I did not simply want to give you the log of failed cases but it may be helpful:

```
Failures:

  1) enumerables #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
     Failure/Error: expect(array.my_all?(3)).to be array.all?(3)
     
     NoMethodError:
       undefined method `is_a' for 3:Integer
       Did you mean?  is_a?
     # ./enumerables.rb:40:in `block in my_all?'
     # ./enumerables.rb:40:in `each'
     # ./enumerables.rb:40:in `each'
     # ./enumerables.rb:40:in `my_all?'
     # ./spec/enumerables_spec.rb:199:in `block (4 levels) in <top (required)>'

  2) enumerables #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
     Failure/Error: expect(array.my_all?(3)).to be array.all?(3)
     
     NoMethodError:
       undefined method `is_a' for 6:Integer
       Did you mean?  is_a?
     # ./enumerables.rb:40:in `block in my_all?'
     # ./enumerables.rb:40:in `each'
     # ./enumerables.rb:40:in `each'
     # ./enumerables.rb:40:in `my_all?'
     # ./spec/enumerables_spec.rb:203:in `block (4 levels) in <top (required)>'

  3) enumerables #my_any? returns true if the block ever returns a value other than false or nil
     Failure/Error: expect(array.my_any?(&true_block)).to eq(array.any?(&true_block))
     
       expected: true
            got: nil
     
       (compared using ==)
     # ./spec/enumerables_spec.rb:212:in `block (3 levels) in <top (required)>'

  4) enumerables #my_any? returns false if the block ever returns a value false or nil::range
     Failure/Error: expect(range.my_any?(&false_block)).to eq(range.any?(&false_block))
     
     NoMethodError:
       undefined method `[]' for 5..50:Range
     # ./enumerables.rb:63:in `block in my_any?'
     # ./enumerables.rb:10:in `block in my_each'
     # ./enumerables.rb:10:in `times'
     # ./enumerables.rb:10:in `my_each'
     # ./enumerables.rb:63:in `my_any?'
     # ./spec/enumerables_spec.rb:220:in `block (3 levels) in <top (required)>'

  5) enumerables #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
     Failure/Error: expect(true_array.my_any?).to be true_array.any?
     
       expected true
            got #<Enumerator:2540> => #<Enumerator: [nil, false, true, []]:my_any>
     # ./spec/enumerables_spec.rb:232:in `block (4 levels) in <top (required)>'

  6) enumerables #my_any? when no block or argument is given returns false if at least one of the collection is not true
     Failure/Error: expect(false_array.my_any?).to be false_array.any?
     
       expected false
            got #<Enumerator:2560> => #<Enumerator: [nil, false, nil, false]:my_any>
     # ./spec/enumerables_spec.rb:236:in `block (4 levels) in <top (required)>'

  7) enumerables #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
     Failure/Error: expect(array.my_any?(Numeric)).to be array.any?(Numeric)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./enumerables.rb:60:in `my_any?'
     # ./spec/enumerables_spec.rb:242:in `block (4 levels) in <top (required)>'

  8) enumerables #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
     Failure/Error: expect(words.my_any?(Integer)).to be words.any?(Integer)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./enumerables.rb:60:in `my_any?'
     # ./spec/enumerables_spec.rb:246:in `block (4 levels) in <top (required)>'

  9) enumerables #my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex
     Failure/Error: expect(words.my_any?(/d/)).to be words.any?(/d/)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./enumerables.rb:60:in `my_any?'
     # ./spec/enumerables_spec.rb:252:in `block (4 levels) in <top (required)>'

  10) enumerables #my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
      Failure/Error: expect(words.my_any?(/z/)).to be words.any?(/z/)
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./enumerables.rb:60:in `my_any?'
      # ./spec/enumerables_spec.rb:256:in `block (4 levels) in <top (required)>'

  11) enumerables #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
      Failure/Error: expect(words.my_any?('cat')).to be words.any?('cat')
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./enumerables.rb:60:in `my_any?'
      # ./spec/enumerables_spec.rb:262:in `block (4 levels) in <top (required)>'

  12) enumerables #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern
      Failure/Error: expect(words.my_any?('cat')).to be words.any?('cat')
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./enumerables.rb:60:in `my_any?'
      # ./spec/enumerables_spec.rb:267:in `block (4 levels) in <top (required)>'

  13) enumerables #my_none? returns false if the block ever returns true for all elements
      Failure/Error: expect(array.my_none?(&false_block)).to eq(array.none?(&false_block))
      
        expected: false
             got: nil
      
        (compared using ==)
      # ./spec/enumerables_spec.rb:282:in `block (3 levels) in <top (required)>'

  14) enumerables #my_none? returns false if the block ever returns true for all elements::range
      Failure/Error: expect(range.my_none?(&false_block)).to eq(range.none?(&false_block))
      
      NoMethodError:
        undefined method `[]' for 5..50:Range
      # ./enumerables.rb:74:in `block in my_none?'
      # ./enumerables.rb:10:in `block in my_each'
      # ./enumerables.rb:10:in `times'
      # ./enumerables.rb:10:in `my_each'
      # ./enumerables.rb:74:in `my_none?'
      # ./spec/enumerables_spec.rb:286:in `block (3 levels) in <top (required)>'

  15) enumerables #my_none? when no block or argument is given returns true only if none of the collection members is true
      Failure/Error: expect(false_array.my_none?).to be true
      
        expected true
             got #<Enumerator:2580> => #<Enumerator: [nil, false, nil, false]:my_any>
      # ./spec/enumerables_spec.rb:296:in `block (4 levels) in <top (required)>'

  16) enumerables #my_none? when no block or argument is given returns false only if one of the collection members is true
      Failure/Error: expect(true_array.my_none?).to be false
      
        expected false
             got #<Enumerator:2600> => #<Enumerator: [nil, false, true, []]:my_any>
      # ./spec/enumerables_spec.rb:300:in `block (4 levels) in <top (required)>'

  17) enumerables #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
      Failure/Error: expect(array.my_none?(String)).to be array.my_none?(String)
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./enumerables.rb:71:in `my_none?'
      # ./spec/enumerables_spec.rb:306:in `block (4 levels) in <top (required)>'

  18) enumerables #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
      Failure/Error: expect(array.my_none?(Numeric)).to be array.my_none?(Numeric)
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./enumerables.rb:71:in `my_none?'
      # ./spec/enumerables_spec.rb:310:in `block (4 levels) in <top (required)>'

  19) enumerables #my_none? when a class is passed as an argument returns false if any of the collection is a member of such cla [...]

2021-01-09 22:32 UTC, abredi requested changes
### Status: Require changes ♲

Hi @necmigunduz and @ZawadiSumba66, :clap: You made good progress on this project. :sparkles: I applaud you for your hard work in implementing custom enumerable methods. Most requirements have done :ok_hand:, Kindly fix the following issues.

[REQUIRED]

- [ ] my_inject raises a "LocalJumpError" when no block or argument is given If no block or argument is given 
- [ ] #my_count should be the same as the original count and return the number of items in enum through enumeration::range
- [ ] #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

 
[OPTIONAL]

- [ ] Enable all rubocop rules
- [ ] Refactor your complex methods by extracting a code fragment into a new method

Once you fix the issues, kindly submit another code review. ♲

Happy coding :man::computer:
Abdulaziz Redi Ali | Connect me on Slack

2021-01-10 11:51 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this project. You've also tried to effect the previous changes recommended. However, this is a flexible project where a change in one method might affect the other. 
As a result of this, we're still having some failed test cases. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

**For this review, I used the following variables to test your methods:**
  - ARRAY_SIZE = 100
  - LOWEST_VALUE = 0
  - HIGHEST_VALUE = 9 
  - array = Array.new(ARRAY_SIZE) { rand(LOWEST_VALUE...HIGHEST_VALUE) }
  - block = proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 }
  - words = %w[dog door rod blade]
  - range = Range.new(5, 50)
  - hash = { a: 1, b: 2, c: 3, d: 4, e: 5 }
  - numbers = [1, 2i, 3.14]
  - array_clone = array.clone
  - true_array = [1, true, 'hi', []] 
  - false_array = [1, false, 'hi', []]
  - true_block = proc { |num| num <= HIGHEST_VALUE }
  - false_block = proc { |num| num > HIGHEST_VALUE }

**_Here is a list of the failed test cases:_**

- [ ] #my_all?
- should return false if the block returns false or nil
     - Test case: expect(array.my_all?(&false_block)).to eq(array.all?(&false_block)) 
     - Expected result: true
     - Got: false
- should return false if the block returns false or nil::range
     - Test case: expect(range.my_all?(&false_block)).to eq(range.all?(&false_block))
     - Expected result: false
     - Got: true
- when no block or argument is given, it should return false when one of the collection members is false or nil
     - Test case: expect(false_array.my_all?).to be false_array.all?
     - Expected result: false
     - Got: true
- when a class is passed as an argument, it should return true if all of the collection is a member of such class::Integer
     - Test case: expect(array.my_all?(Integer)).to be array.all?(Integer)
     - Expected result: boolean
     - Got: NameError: undefined local variable or method `arg' for #<Array:0x0000556980dd0c68>
     **_Note: the above case is also applicable when the class is Numeric_**
- when a Regex is passed as an argument, it should return false if any of the collection does not match the Regex
     - Test case: expect(words.my_all?(/o/)).to be words.all?(/o/)
     - Expected: false
     - Got: true
- when a pattern other than Regex or a Class is given, it should return false if any of the collection does not match the pattern
     - Test case: expect(array.my_all?(3)).to be array.all?(3)
     - Expected: false
     - Got: true

- [ ] #my_any?
- when no block or argument is given, it should return false if at least one of the collection is not true
     - Test case: expect(false_array.my_any?).to be false_array.any?
     - Expected: false
     - Got: true
- when a class is passed as an argument, it should return true if at least one of the collection is a member of such class::Integer
      - Test case: expect(words.my_any?(Integer)).to be words.any?(Integer)
      - Expected: false
      - Got: true
- [ ] #my_none?
- when no block or argument is given, it should return true only if none of the collection members is true
      - Test case: expect(false_array.my_none?).to be true
      - Expected: true
      - Got: false
- [ ] #my_inject
- should raise a "LocalJumpError" when no block or argument is given
      - Test case: expect { array.my_inject }.to raise_error(LocalJumpError)
      - Expected LocalJumpError
      - Got:  #<NameError: undefined local variable or method `number' for #<Array:0x0000556980e317e8>> 
- when a symbol is specified without an initial value, it should combine each element of the collection by applying the symbol as a named method
      - Test case: expect(array.my_inject(:+)).to eq array.inject(:+)
      - Expected: true
      - Got: NameError: undefined local variable or method `number' for #<Array:0x0000556980e72608>

**We understand how challenging this project is. Please, do not give up. You should be careful with making new changes so that the new changes do not affect the already passed test cases.**



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-01-10 14:50 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  Congratulations 🎊 👏, you did very well on this project.

[Required]

- [ ] If a class passed as an argument, and all of the collection is a member of a given class #my_all?, and #my_any? should return true.

	E.g. 
	```
	[2 ,3, 4].my_all?(Numeric)  # => true
	[1, 2, 3].my_all?(Integer) # => true
	```
 

- [ ] #my_inject should raise a "LocalJumpError" when no block or argument is given.

	e.g. array.my_inject

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2021-01-10 23:19 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  I appreciate your hard work in achieving this milestone; you did very well.

[Required]
 

- [ ] #my_inject should raise (not return) a "LocalJumpError" when no block or argument is given.

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2021-01-10 23:19 UTC, abredi commented on enumerables.rb
> +      LocalJumpError.new 'no block given'
`raise LocalJumpError, 'no block is given', caller` instead of returning an obect.

2021-01-11 04:07 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @necmigunduz and @ZawadiSumba66  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, but you still have some cases that you need to cover for `#my_inject` method, 
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Make sure to remove `.vscode` folder from your repository, it's not related to your project, so you don't need to commit it to your repo.
- [ ] The license link in your readme file redirects on empty document, that is making your repo to look unprofessional, please fix that issue by adding actual content of the appropriate license or you can simply remove the link
- [ ] Cover the four cases that I highlighted in inline comments directly in your codes,
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-01-11 04:07 UTC, descholar-ceo commented on enumerables.rb
> +  end
## #my_inject should have the following behaviors:
- [ ]  when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- [ ] when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- [ ] when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- [ ] when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range

2021-01-11 06:55 UTC, descholar-ceo commented
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

2021-01-11 07:02 UTC, descholar-ceo approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @necmigunduz and @ZawadiSumba66  , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2021-01-21 13:20 UTC, merged